### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by vborchsh** [catkira/py3gpp#1]
Dear Benjamin,

Very interesting work! Actually, I do the  same things and I will be happy to contribute in the project instead of standalone mess. You will find my stuff here: https://github.com/vborchsh/pynrl1/tree/develop/pynrl1

So, I have couple of questions:

1. What would you mind about refactoring repo structure for clear division between tests and functional modules? It won't affect to ipynb examples or any other.
 
2. Github CI obviously has no MATALB instance. I cover Python modules with MATLAB references thanks to Python API. May I keep it "as is" for offline checks?

**Comment by catkira** [comment]
Hi,

1. yes I think that would be good
2. I don't understand that, can You give an example of a "MATLAB reference"?

**Comment by vborchsh** [comment]
> I don't understand that, can You give an example of a "MATLAB reference"?

Example:
https://github.com/vborchsh/pynrl1/blob/develop/tests/test_nrPBCH.py

In this test I use Python's matlab.engine for call MATLAB functions such as ```eng.nrPBCH(...)``` literally from MATLAB. Then, I use MATLAB arrays to check my Python's implementation.

Details about MATLAB API:
https://www.mathworks.com/help/matlab/matlab-engine-for-python.html

**Comment by catkira** [comment]
Ah I see. Yes I think it does not hurt if they are kept in the code, as long as there are still pure python tests which can run without Matlab.
I had a quick look at Your code, so far the things You implemented look fairly identical to the ones I did. What is Your plan for implementing next?

**Comment by vborchsh** [comment]
I concentrated on downlink part. So, I'm going to implement PDSCHDMRS+Indices, PDSCHPTRS+Indices and PDCCH+Indices functions to cover my current work. Then - PDSCH in general, probably, with limited functionality in the beginning.

**Comment by catkira** [comment]
that sounds good. PRs are welcome.

**Comment by vborchsh** [comment]
Ok, let me close current issue and I'll come back later with PRs. Thanks!
