### ISSUE TITLE
CI lint error

### ISSUE THREAD

**Issue by catkira** [catkira/py3gpp#12]
![image](https://user-images.githubusercontent.com/13425558/234502679-bd1f575b-4b34-4805-96e3-190afd143eac.png)

**Comment by vborchsh** [comment]
Definitely because of issues with access to git pages.

Are you planning to publish something there? Because I see no open pages at this address: https://catkira.github.io/py3gpp/

**Comment by catkira** [comment]
No, I did not plan to publish anything there. I created the github page only for the purpose to link the lint badge in README.md. Deployment artifacts are not easy to link to from outside, and I think the problem was that deployment artifacts are always packed. So it was not possible to have the badge deployed in a way that I can use in README.md.

It was working before, why is it not working anymore now?

**Comment by vborchsh** [comment]
It is work, but for `master` branch only. Due to github rules, or some environment settings, no idea, what exactly.

You can check Settings -> Environments -> <env-name> -> Deployment branches. It could be switched to `All branches`, or something like that.

**Comment by catkira** [comment]
The dev branch is gone, so that problem is solved. But it also fails for the release tag "v0.1.6"

**Comment by catkira** [comment]
![image](https://user-images.githubusercontent.com/13425558/234524821-5ec65bd5-a933-4868-9f07-6db525d559e6.png)
Ah ok its here, only master is allowed to deploy the pylint badge. But that makes sense. So we should disable the badge deployment in the CI script for all runs that are not master.

**Comment by vborchsh** [comment]
TBH, I never did these tricks with badges) So, please, go ahead with it.

**Comment by catkira** [comment]
ok I will try to figure it out

**Comment by catkira** [comment]
I am trying to fix this here https://github.com/catkira/py3gpp/pull/15

**Comment by vborchsh** [comment]
As an idea: we can try to split linting and badges deploying in two steps. Not sure, how to synchronize artifacts, but still

**Comment by catkira** [comment]
fixed with this PR https://github.com/catkira/py3gpp/pull/17

**Comment by vborchsh** [comment]
Ok, I see linting work. But we need to test releasing to pypi. I'm not 100% sure that this part of CI works.
