### ISSUE TITLE
CI publish

### ISSUE THREAD

**Issue by vborchsh** [catkira/py3gpp#18]
Ok, I see linting works. But we need to test releasing to pypi. I'm not 100% sure that this part of CI works.

I think, there is a possibility to delete existing release (0.1.6) from WEB interface and create new one. This will trigger CI with the last step.

**Comment by catkira** [comment]
fixed with this commit [757d69ccff5a3b2bf1adfb472036df6d80abfb5c](https://github.com/catkira/py3gpp/commit/757d69ccff5a3b2bf1adfb472036df6d80abfb5c)
