### ISSUE TITLE
pypi upload is not working anymore

### ISSUE THREAD

**Issue by catkira** [catkira/py3gpp#38]
@vborchsh do You know why?

**Comment by vborchsh** [comment]
Hi,

I see this: https://github.com/catkira/py3gpp/blob/7c0916b4cbfb92b813ba9a92f0b1ad1cb5cd65cc/.github/workflows/lint_and_test.yml#L81C48-L81C48

Try to create new release from Github web: 
![image](https://github.com/catkira/py3gpp/assets/22661151/56ba814e-da92-4f07-b466-b77226114ba6)

But maybe I wrong...

**Comment by catkira** [comment]
ah yes, I am stupid. I forgot I have to create a release. Thanks!
