### ISSUE TITLE
nrPathLossConfig() unable to call object

### ISSUE THREAD

**Issue by zulfadlizainal** [catkira/py3gpp#56]
![image](https://github.com/catkira/py3gpp/assets/50709439/f4e35e29-ff8e-45ce-979e-5b8c21133bd8)

unable to call object like matlab due to property stored as a dictionary in the config files. 

i will submit pr to fix it.

**Comment by catkira** [comment]
Can you name the properties with underscore at the beginning, like `_Scenaria` and then add get and setter routines for each attribute. You can have a look at the other config classes to see how we did it.

**Comment by zulfadlizainal** [comment]
ok let me check out the format

**Comment by zulfadlizainal** [comment]
Closing the issue with above PR. Thanks!

Object call now successful:
![image](https://github.com/catkira/py3gpp/assets/50709439/381bbc87-b553-4b8f-8f0b-05746fd266de)
