### ISSUE TITLE
nrPathLoss() rural macro path loss model result have ~+/-0.5db inaccuracy

### ISSUE THREAD

**Issue by zulfadlizainal** [catkira/py3gpp#57]
![image](https://github.com/catkira/py3gpp/assets/50709439/1b26c6a4-1871-483e-9ebd-bd01eaa3e8e6)

I have sometime this afternoon, i will review again calculation from TR 38.901.

**Comment by catkira** [comment]
Thanks!
Can you also add a test in the tests/matlab folder that compares it directly with matlab?

**Comment by zulfadlizainal** [comment]
Close this issue with above pr.

Fix some math syntax and get similar result as matlab docs.
![image](https://github.com/catkira/py3gpp/assets/50709439/8e860665-9545-4da7-89b6-bfa9eaddbb30)

**Comment by catkira** [comment]
can you also add a hardcoded test for this?

**Comment by catkira** [comment]
I did that already.

**Comment by zulfadlizainal** [comment]
thanks for supporting :)
