### ISSUE TITLE
`nrCRCEncode` returns tricky array

### ISSUE THREAD

**Issue by vborchsh** [catkira/py3gpp#60]
It returns numpy ndarray, which is multidimentional array. Obviously, this because of `blk = np.expand_dims(blk, axis = 1)` .

So, now I need:
```
encoded_bits = nrCRCEncode(ref_bits, crc_type).T[0]
```
instead of:
```
encoded_bits = nrCRCEncode(ref_bits, crc_type)
```

is there a reason to keep it like this?

**Comment by catkira** [comment]
I think it is like that because nrCRCEncode can process multiply blocks at once in matlab. So the extra axis is kept to have the same return interface if one or more blocks are given as input.

**Comment by vborchsh** [comment]
Ah, ok, I see
