### ISSUE TITLE
nrPDSCHDMRSIndices() throws error

### ISSUE THREAD

**Issue by catkira** [catkira/py3gpp#66]
When I try to execute this code
```python
cfg = nrPDSCHConfig()
dmrsIndices = nrPDSCHDMRSIndices(cfg)
```
I get this error:
<img width="470" alt="image" src="https://github.com/catkira/py3gpp/assets/13425558/9df75194-3212-4ffb-b214-90162d662226">

@vborchsh Do you have an idea where the problem is?

**Comment by catkira** [comment]
Ah I think it's because NRBSize has no default value. Should we add a default value for it?

**Comment by vborchsh** [comment]
Yes, I think so

**Comment by vborchsh** [comment]
Weird, NRBSize is 12 by default. I'll dig in...

**Comment by catkira** [comment]
It could be that I already fixed it with [this](https://github.com/catkira/py3gpp/commit/0dfb9e26cc48fb42baacd077c2fafa8f1adec880) commit
